name: Publicar Post Automático Diário

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai

      - name: Rodar o script de criação do post
        env:
          # --- CORREÇÃO ESTÁ AQUI ---
          # Trocamos a chave antiga pela nova da GNews
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        run: python main.py
