name: Publicar Explicador de Tendências

on:
  workflow_dispatch:
  schedule:
    # Agendado para uma vez ao dia, às 8h da manhã.
    - cron: '0 11 * * *'

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          # Instala as bibliotecas necessárias para o novo script
          pip install requests google-generativeai pytrends

      - name: Rodar o script de criação do post
        env:
          # Passando apenas os 3 segredos que o novo script precisa
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        run: python main.py
