# Nome do nosso workflow de automação
name: Publicar Post Automático Diário

# Define quando a automação vai rodar
on:
  # Permite que a gente rode manualmente pela interface do GitHub (para testes)
  workflow_dispatch:
  
  # Agenda para rodar automaticamente todos os dias
  schedule:
    # Este cron '0 11 * * *' roda todo dia às 11:00 UTC, que são 08:00 no horário de Brasília.
    - cron: '0 11 * * *'

# Define as tarefas que a automação vai executar
jobs:
  build-and-post:
    # Usa um ambiente virtual do Linux (Ubuntu) para rodar nosso código
    runs-on: ubuntu-latest
    
    # Define os passos da tarefa
    steps:
      # 1. Baixa o código do seu repositório para o ambiente virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python na versão 3.10
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala as bibliotecas que o nosso script main.py precisa
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai

      # 4. Roda o script principal (main.py)
      - name: Rodar o script de criação do post
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        run: python main.py
