name: Publicar Post Automático Diário

on:
  workflow_dispatch:
  schedule:
    # Agenda para rodar 3 vezes ao dia (horário de Brasília)
    - cron: '0 9 * * *'   # Roda às 06:00
    - cron: '50 14 * * *' # Roda às 11:50
    - cron: '50 20 * * *' # Roda às 17:50

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai

      - name: Rodar o script de criação do post
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        run: python main.py
