name: Publicar Explicador de Tendências

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          # MUDANÇA AQUI: instalando a biblioteca do SerpApi
          pip install requests google-generativeai google-search-results

      - name: Rodar o script de criação do post
        env:
          # MUDANÇA AQUI: Passando os segredos necessários
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python main.py
